CREATE TABLE "webhook_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"gateway_name" text NOT NULL,
	"gateway_event_id" text NOT NULL,
	"event_type" text NOT NULL,
	"gateway_payment_id" text NOT NULL,
	"gateway_order_id" text,
	"payment_transaction_id" uuid,
	"payload" jsonb NOT NULL,
	"signature" text,
	"processed_at" timestamp with time zone NOT NULL,
	"processing_status" text DEFAULT 'success',
	"error_message" text,
	"retry_count" integer DEFAULT 0,
	"user_id" uuid,
	"subscription_id" uuid,
	CONSTRAINT "uq_gateway_event" UNIQUE("gateway_name","gateway_event_id")
);
--> statement-breakpoint
ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_renewal_price_strategy_check";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_previous_subscription_id_fkey";
--> statement-breakpoint
ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_upgrade_from_plan_id_fkey";
--> statement-breakpoint
ALTER TABLE "subscriptions" DROP CONSTRAINT "subscriptions_upgrade_from_pricing_id_fkey";
--> statement-breakpoint
ALTER TABLE "doctor_plan_features" ADD COLUMN "max_assignments_per_month" integer;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "gateway_name" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "gateway_payment_id" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "gateway_order_id" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "webhook_event_id" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "webhook_processed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "refund_reference_id" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "refund_reason" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "refund_amount" numeric;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "refund_history_id" bigint;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "created_by_user_id" bigint;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "updated_by_user_id" bigint;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "source_user_id" bigint;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "source_text" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "gateway_bank" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "gateway_wallet" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "gateway_vpa" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "invoice_number" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "receipt_number" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "response_message" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "payment_status" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "payment_type" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "verified_via" text;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "user_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "subscription_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "plan_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD COLUMN "pricing_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_events" ADD CONSTRAINT "webhook_events_payment_transaction_id_fkey" FOREIGN KEY ("payment_transaction_id") REFERENCES "public"."payment_transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_webhook_events_event_type" ON "webhook_events" USING btree ("event_type" text_ops);--> statement-breakpoint
CREATE INDEX "idx_webhook_events_gateway_order" ON "webhook_events" USING btree ("gateway_name" text_ops,"gateway_order_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_webhook_events_gateway_payment" ON "webhook_events" USING btree ("gateway_name" text_ops,"gateway_payment_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_webhook_events_processed_at" ON "webhook_events" USING btree ("processed_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_webhook_events_status" ON "webhook_events" USING btree ("processing_status" text_ops);--> statement-breakpoint
CREATE INDEX "idx_webhook_events_transaction" ON "webhook_events" USING btree ("payment_transaction_id" uuid_ops) WHERE (payment_transaction_id IS NOT NULL);--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."subscription_plans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_pricing_id_fkey" FOREIGN KEY ("pricing_id") REFERENCES "public"."plan_pricing"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_orders_user_plan" ON "orders" USING btree ("user_id" uuid_ops,"plan_id" uuid_ops) WHERE (order_type = 'subscription'::text);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_created_at" ON "payment_transactions" USING btree ("created_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_gateway_order" ON "payment_transactions" USING btree ("gateway_name" text_ops,"gateway_order_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_order" ON "payment_transactions" USING btree ("order_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_payment_status" ON "payment_transactions" USING btree ("payment_status" text_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_status" ON "payment_transactions" USING btree ("payment_status" text_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_type_status" ON "payment_transactions" USING btree ("payment_type" text_ops,"payment_status" text_ops);--> statement-breakpoint
CREATE INDEX "idx_payment_transactions_webhook_event" ON "payment_transactions" USING btree ("webhook_event_id" text_ops) WHERE (webhook_event_id IS NOT NULL);--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "price_at_purchase";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "currency_at_purchase";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "plan_snapshot";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "features_at_purchase";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "renewal_price_strategy";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "renewal_count";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "previous_subscription_id";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "upgrade_from_plan_id";--> statement-breakpoint
ALTER TABLE "subscriptions" DROP COLUMN "upgrade_from_pricing_id";--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD CONSTRAINT "uq_gateway_payment" UNIQUE("gateway_name","gateway_payment_id");--> statement-breakpoint
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_verified_via_check" CHECK (verified_via = ANY (ARRAY['webhook'::text, 'manual'::text]));